version: "3"

services:
  rust-blog-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USERNAME=rustblog
      - POSTGRESQL_PASSWORD=rustblog
      - POSTGRESQL_DATABASE=rustblog
  rustblog-api-pgadmin:
    image: dpage/pgadmin4
    ports:
      - 82:80
    environment:
      - PGADMIN_DEFAULT_EMAIL=rustblog@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=rustblog
